### PR TITLE
skip unsignable headers

### LINKED ISSUE #1198: Requests signed with "connection" header are rejected by AWS
**Describe the bug**

Requests with "connection" header are rejected by API Gateway HTTP API with IAM auth.

**To Reproduce**

* Create an HTTP API in API Gateway (e.g. [`aws apigatewayv2 create-api`](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/apigatewayv2/create-api.html))
* Add IAM auth to this API
* Send a request with "connection: keep-alive" header to this API, signed using this package with appropriate AWS creds
* Receive 403 `{"message":"Forbidden"}` response

Sample code
```csharp
Environment.SetEnvironmentVariable("AWS_PROFILE", "<my-profile>");

var client = new HttpClient();

var request = new HttpRequestMessage(HttpMethod.Get, "<api-gateway-http-api-url>")
{
	Headers = {
		{ "Connection", ["keep-alive"] },
	},
};

var response = await client.SendAsync(
	request,
	"<region>",
	"execute-api",
	Amazon.Runtime.FallbackCredentialsFactory.GetCredentials()
);

Console.WriteLine(response.StatusCode);
Console.WriteLine(await response.Content.ReadAsStringAsync());
```

**Expected behavior**

The request is accepted.

**Desktop (please complete the following information):**

Windows 10 & Amazon Linux 2023

**Additional context**

Although not explicitly documented, it looks like AWS simply doesn't accept some headers in the signature (they accept them in the request, but not in the signature calculation).
See an explicit case here with the "connection" header: https://repost.aws/questions/QUWXtAMiggShedgHG3hLl3tg/ses-sigv4-usage-update-connection-header

Other libraries (including AWS SDKs) deal with this by hardcoding (& maintaining) a list of unsignable headers and/or allow users to supply a list of headers to sign/not sign.
e.g.
- https://github.com/mhart/aws4/issues/119
- https://github.com/aws/aws-sdk-java-v2/blob/7da518ab63807ac633951afc39fb833b361d7aeb/core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java#L70-L71
- https://github.com/aws/aws-sdk-net/blob/acae479fe47dc2583f625fe9f3d68413573ee15b/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L61-L66
- https://github.com/aws/aws-sdk-js/blob/cc29728c1c4178969ebabe3bbe6b6f3159436394/lib/signers/v4.js#L190-L198

Supporting customization also makes it possible to use this package in environments where a proxy may alter request headers.

### PR DESCRIPTION
**Pull request by cfbao**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.

- Fixes #1198

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/Private/CanonicalRequest.cs [hunk 1]
```diff
@@ -30,6 +30,24 @@ public static class CanonicalRequest
...
+            "proxy-authenticate",
+            "proxy-authorization",
+            "proxy-connection",
+            "range",
+            "te",
+            "trailer",
+            "transfer-encoding",
+            "upgrade",
+            HeaderKeys.XAmznTraceIdHeader,
+        };
```
Comment (cfbao) [inline src/Private/CanonicalRequest.cs]: Sources I used to come up with this list:
- primarily [@smithy/signature-v4](https://github.com/smithy-lang/smithy-typescript/blob/430021abf44f8a4d6c24de2dfa25709bf91a92c8/packages/signature-v4/src/constants.ts#L19-L35) (used by AWS SDK for JavaScript)
- [AWS SDK for Java](https://github.com/aws/aws-sdk-java-v2/blob/47fcc27deb90d4102ca5b76c35d27749b1ca0e08/core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAws4Signer.java#L70-L71)
- [AWS SDK for .NET](https://github.com/aws/aws-sdk-net/blob/b8431ed566827a081624a558d7d76b35ecf5f04d/sdk/src/Core/Amazon.Runtime/Internal/Auth/AWS4Signer.cs#L61-L66)
- [aws4fetch](https://github.com/mhart/aws4fetch/blob/629b108747e066d1b93e8b72a4adbf2a4220db3b/src/main.js#L22-L33)

The final list here is still quite conservative - all headers listed here have been verified to always cause invalid signatures with an IAM-protected API Gateway REST API endpoint.
Most of them are standard hop-by-hop headers (see [list on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection)), and it makes total sense to not sign them.

Some headers are unsigned by the libraries referenced above, but not included here, e.g.
- AWS SDK for .NET ignores `amz-sdk-invocation-id` and `amz-sdk-request`, but only because of their specific retry behaviour, which isn't relevant here. See https://github.com/aws/aws-sdk-net/commit/9017e427ebcd0b1aa60b3ba472ba74282a3348be
- @smithy/signature-v4 skips many browser specific headers that are likely not relevant here

Quite a few libraries also ignore the `user-agent` header in the signature. I'm not sure if they encountered similar issues to https://github.com/FantasticFiasco/aws-signature-version-4/issues/1155 or if there's another reason. In any case, the user-agent header doesn't cause signature problems in the latest version of AwsSignatureVersion4 in my testing.

Comment (FantasticFiasco) [reply src/Private/CanonicalRequest.cs]: Thanks for analyzing the other libraries and creating a coherent list of headers to ignore.

I've created #1208 to analyze the `User-Agent` header, potentially opening up to ignore the header instead of implementing a workaround for it.

**Comment by FantasticFiasco** [comment]
I'm sorry it is taking this time, but we will eventually get there. I'm looking into extending the tests running against the API Gateway.

File: test/Unit/Private/CanonicalRequestShould.cs [hunk 2]
```diff
@@ -223,6 +256,23 @@ public void SortQueryParameterValues(string query, string parameterName, string[
...
+            foreach (var testCase in UnsignableHeadersTestCases)
+            {
+                var headerName = (string)testCase[0];
+                var headerValue = (string)testCase[0];
+
+                // Exclude the following headers due to them failing
+                if (headerValue is "Range" or "Transfer-Encoding")
+                {
+                    continue;
+                }
```
Comment (cfbao) [inline test/Unit/Private/CanonicalRequestShould.cs:270]: Should it have been `var headerValue = (string)testCase[1];`?
Maybe then we don't need to skip Range or Transfer-Encoding headers in tests.
